### ISSUE TITLE
Confusion: Can't use binary search in the 2.1 DNA Search when the gene are not sorted

### ISSUE THREAD

**Issue by theonlyNischal** [davecom/ClassicComputerScienceProblemsInPython#18]
In the code that you provided, the gene sequence is not explicitly sorted, so the binary search algorithm will not work correctly on this gene sequence.

**Comment by davecom** [comment]
Not sure what you're referring to. It's sorted on line 67 and then searched:
```
my_sorted_gene: Gene = sorted(my_gene)
print(binary_contains(my_sorted_gene, acg))  # True
print(binary_contains(my_sorted_gene, gat))  # False
```
