### ISSUE TITLE
nucleotides dictionary

### ISSUE THREAD

**Issue by GreatBahram** [davecom/ClassicComputerScienceProblemsInPython#5]
Hi, first of all thanks for your great book.
You could just save the nucleotide inside a dictionary, instead of iterating on each one.
```python
NUCLEOTIDES_MAP = {
    'A': 0b00,
    'C': 0b01,
    'G': 0b10,
    'T': 0b11,
}
RMAP = {v: k for k, v in NUCLEOTIDES_MAP.items()}
```
https://github.com/davecom/ClassicComputerScienceProblemsInPython/blob/57d5f945e20eab0b88bea202d5a01e7318a5a613/Chapter1/trivial_compression.py#L24-L30

**Comment by GreatBahram** [comment]
Moreover, you could pass `self.bit_string` to `bin` function which returns a binary string representation. Then split the text into two-character group, and each of which would be a nucleotide. What's the benefit? In this case, you don't need to `bitwise` anything or reverse the output.

**Comment by GreatBahram** [comment]
You're totally right, last paragraph make everything clear.

**Comment by davecom** [comment]
Hi @GreatBahram ,
Sorry for not replying sooner. Yes, I was going to point you to that paragraph.
Thanks for reading,
Dave
