### ISSUE TITLE
Deque() should be deque() in Chapter2/generic_search.py

### ISSUE THREAD

**Issue by HayaoSuzuki** [davecom/ClassicComputerScienceProblemsInPython#6]
In `Chapter2/generic_search.py` class `Queue` was defined as follows.

```python
class Queue(Generic[T]):
    def __init__(self) -> None:
        self._container: Deque[T] = Deque()
```

I think that class `Quene` should be defined as follows. 
I use `collections.deque` instead of `typing.Deque`.

```python
from collections import deque

class Queue(Generic[T]):
    def __init__(self) -> None:
        self._container: Deque[T] = deque()
```

**Comment by davecom** [comment]
Hi Hayao,
Thanks for reaching out. The Deque class from typing.Deque is just a generic analog of the collections.deque class. So, it's really the same thing internally.

> class typing.Deque(deque, MutableSequence[T])
A generic version of collections.deque.

https://docs.python.org/3/library/typing.html
Best,
David
